/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mistNode_MistNode */

#ifndef _Included_mistNode_MistNode
#define _Included_mistNode_MistNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mistNode_MistNode
 * Method:    startMistApp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_startMistApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mistNode_MistNode
 * Method:    stopMistApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_stopMistApp
  (JNIEnv *, jobject);

/*
 * Class:     mistNode_MistNode
 * Method:    addEndpoint
 * Signature: (LmistNode/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_addEndpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mistNode_MistNode
 * Method:    removeEndpoint
 * Signature: (LmistNode/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_removeEndpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mistNode_MistNode
 * Method:    readResponse
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_readResponse
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     mistNode_MistNode
 * Method:    readError
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_readError
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

/*
 * Class:     mistNode_MistNode
 * Method:    writeResponse
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_writeResponse
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     mistNode_MistNode
 * Method:    writeError
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_writeError
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

/*
 * Class:     mistNode_MistNode
 * Method:    invokeResponse
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_invokeResponse
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     mistNode_MistNode
 * Method:    invokeError
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_invokeError
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

/*
 * Class:     mistNode_MistNode
 * Method:    changed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_changed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mistNode_MistNode
 * Method:    request
 * Signature: ([B[BLmistNode/MistNode/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_mistNode_MistNode_request
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     mistNode_MistNode
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mistNode_MistNode_requestCancel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class mistNode_MistNode_RequestCb */

#ifndef _Included_mistNode_MistNode_RequestCb
#define _Included_mistNode_MistNode_RequestCb
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class mistNode_MistNode_MistNodeHolder */

#ifndef _Included_mistNode_MistNode_MistNodeHolder
#define _Included_mistNode_MistNode_MistNodeHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
