/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mist_api_MistApi */

#ifndef _Included_mist_api_MistApi
#define _Included_mist_api_MistApi
#ifdef __cplusplus
extern "C" {
#endif
#undef mist_api_MistApi_MIST_API_SUCCESS
#define mist_api_MistApi_MIST_API_SUCCESS 0L
#undef mist_api_MistApi_MIST_API_ERROR_MULTIPLE_TIMES
#define mist_api_MistApi_MIST_API_ERROR_MULTIPLE_TIMES -1L
#undef mist_api_MistApi_MIST_API_ERROR_UNSPECIFIED
#define mist_api_MistApi_MIST_API_ERROR_UNSPECIFIED -10L
/*
 * Class:     mist_api_MistApi
 * Method:    startMistApi
 * Signature: (Ljava/lang/String;Lmist/node/MistNode;Laddon/WishFile;)I
 */
JNIEXPORT jint JNICALL Java_mist_api_MistApi_startMistApi
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     mist_api_MistApi
 * Method:    stopMistApi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mist_api_MistApi_stopMistApi
  (JNIEnv *, jobject);

/*
 * Class:     mist_api_MistApi
 * Method:    request
 * Signature: ([BLmist/api/MistApi/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_mist_api_MistApi_request
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     mist_api_MistApi
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mist_api_MistApi_requestCancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     mist_api_MistApi
 * Method:    sandboxedRequest
 * Signature: ([B[BLmist/api/MistApi/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_mist_api_MistApi_sandboxedRequest
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     mist_api_MistApi
 * Method:    sandboxedRequestCancel
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_mist_api_MistApi_sandboxedRequestCancel
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class mist_api_MistApi_RequestCb */

#ifndef _Included_mist_api_MistApi_RequestCb
#define _Included_mist_api_MistApi_RequestCb
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class mist_api_MistApi_MistApiHolder */

#ifndef _Included_mist_api_MistApi_MistApiHolder
#define _Included_mist_api_MistApi_MistApiHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
