/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mistApi_MistApi */

#ifndef _Included_mistApi_MistApi
#define _Included_mistApi_MistApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mistApi_MistApi
 * Method:    startMistApi
 * Signature: (Ljava/lang/String;LmistNode/MistNode;Laddon/WishFile;)V
 */
JNIEXPORT void JNICALL Java_mistApi_MistApi_startMistApi
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     mistApi_MistApi
 * Method:    stopMistApi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mistApi_MistApi_stopMistApi
  (JNIEnv *, jobject);

/*
 * Class:     mistApi_MistApi
 * Method:    request
 * Signature: ([BLmistApi/MistApi/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_mistApi_MistApi_request
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     mistApi_MistApi
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mistApi_MistApi_requestCancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     mistApi_MistApi
 * Method:    sandboxedRequest
 * Signature: ([B[BLmistApi/MistApi/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_mistApi_MistApi_sandboxedRequest
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     mistApi_MistApi
 * Method:    sandboxedRequestCancel
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_mistApi_MistApi_sandboxedRequestCancel
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class mistApi_MistApi_RequestCb */

#ifndef _Included_mistApi_MistApi_RequestCb
#define _Included_mistApi_MistApi_RequestCb
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class mistApi_MistApi_MistApiHolder */

#ifndef _Included_mistApi_MistApi_MistApiHolder
#define _Included_mistApi_MistApi_MistApiHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
