/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_mist_api_wish_WishCoreApiJni */

#ifndef _Included_fi_ct_mist_api_wish_WishCoreApiJni
#define _Included_fi_ct_mist_api_wish_WishCoreApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_mist_api_wish_WishCoreApiJni
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_api_wish_WishCoreApiJni_register
  (JNIEnv *, jobject);

/*
 * Class:     fi_ct_mist_api_wish_WishCoreApiJni
 * Method:    receive_wish_api
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_mist_api_wish_WishCoreApiJni_receive_1wish_1api
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class fi_ct_mist_api_wish_WishCoreApiJni_CallbackList */

#ifndef _Included_fi_ct_mist_api_wish_WishCoreApiJni_CallbackList
#define _Included_fi_ct_mist_api_wish_WishCoreApiJni_CallbackList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
