/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class addon_WishBridgeJni */

#ifndef _Included_addon_WishBridgeJni
#define _Included_addon_WishBridgeJni
#ifdef __cplusplus
extern "C" {
#endif
#undef addon_WishBridgeJni_BRIDGE_CONNECTED
#define addon_WishBridgeJni_BRIDGE_CONNECTED 32L
/*
 * Class:     addon_WishBridgeJni
 * Method:    register
 * Signature: (Laddon/WishBridge;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_addon_WishBridgeJni_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     addon_WishBridgeJni
 * Method:    receive_core_to_app
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_addon_WishBridgeJni_receive_1core_1to_1app
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     addon_WishBridgeJni
 * Method:    connected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_addon_WishBridgeJni_connected
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
