/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wishApp_WishApp */

#ifndef _Included_wishApp_WishApp
#define _Included_wishApp_WishApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wishApp_WishApp
 * Method:    startWishApp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_wishApp_WishApp_startWishApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wishApp_WishApp
 * Method:    stopWishApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wishApp_WishApp_stopWishApp
  (JNIEnv *, jobject);

/*
 * Class:     wishApp_WishApp
 * Method:    request
 * Signature: ([BLwishApp/WishApp/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_wishApp_WishApp_request
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     wishApp_WishApp
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wishApp_WishApp_requestCancel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class wishApp_WishApp_RequestCb */

#ifndef _Included_wishApp_WishApp_RequestCb
#define _Included_wishApp_WishApp_RequestCb
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wishApp_WishApp_MistNodeHolder */

#ifndef _Included_wishApp_WishApp_MistNodeHolder
#define _Included_wishApp_WishApp_MistNodeHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
