/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mist_WishBridgeJni */

#ifndef _Included_mist_WishBridgeJni
#define _Included_mist_WishBridgeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mist_WishBridgeJni
 * Method:    register
 * Signature: (Lmist/WishBridge;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mist_WishBridgeJni_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mist_WishBridgeJni
 * Method:    receive_core_to_app
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_mist_WishBridgeJni_receive_1core_1to_1app
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     mist_WishBridgeJni
 * Method:    connected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_mist_WishBridgeJni_connected
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
