/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wish_WishApp */

#ifndef _Included_wish_WishApp
#define _Included_wish_WishApp
#ifdef __cplusplus
extern "C" {
#endif
#undef wish_WishApp_WISH_APP_SUCCESS
#define wish_WishApp_WISH_APP_SUCCESS 0L
#undef wish_WishApp_WISH_APP_ERROR_MULTIPLE_TIMES
#define wish_WishApp_WISH_APP_ERROR_MULTIPLE_TIMES -1L
#undef wish_WishApp_WISH_APP_ERROR_UNSPECIFIED
#define wish_WishApp_WISH_APP_ERROR_UNSPECIFIED -10L
/*
 * Class:     wish_WishApp
 * Method:    startWishApp
 * Signature: (Ljava/lang/String;Laddon/WishFile;)I
 */
JNIEXPORT jint JNICALL Java_wish_WishApp_startWishApp
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     wish_WishApp
 * Method:    stopWishApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wish_WishApp_stopWishApp
  (JNIEnv *, jobject);

/*
 * Class:     wish_WishApp
 * Method:    request
 * Signature: ([BLwish/WishApp/RequestCb;)I
 */
JNIEXPORT jint JNICALL Java_wish_WishApp_request
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     wish_WishApp
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wish_WishApp_requestCancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     wish_WishApp
 * Method:    bsonConsolePrettyPrinter
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_wish_WishApp_bsonConsolePrettyPrinter
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class wish_WishApp_RequestCb */

#ifndef _Included_wish_WishApp_RequestCb
#define _Included_wish_WishApp_RequestCb
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wish_WishApp_Error */

#ifndef _Included_wish_WishApp_Error
#define _Included_wish_WishApp_Error
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wish_WishApp_MistNodeHolder */

#ifndef _Included_wish_WishApp_MistNodeHolder
#define _Included_wish_WishApp_MistNodeHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
